version: 2
project_name: pdfsigner
builds:
- id: pdfsigner-linux
  goos:
  - linux
  goarch:
  - amd64
  - arm64
  ldflags:
  - -s -w
  - -X main.BuildDate={{ .Date }}
  - -X main.Version={{ .ShortCommit }}
  - -X main.GitCommit={{ .FullCommit }}
  - -X main.GitBranch={{ .Branch }}
  flags:
  - -trimpath
  env:
  - CGO_ENABLED=1
  - >-
      {{- if eq .Os "linux" }}
        {{- if eq .Arch "amd64" }}CC=zig c -target x86_64-linux-musl{{- end }}
        {{- if eq .Arch "arm64"}}CC=zig c -target aarch64-linux-musl{{- end }}
      {{- end }}
  - >-
      {{- if eq .Os "linux" }}
        {{- if eq .Arch "amd64" }}CC=zig c++ -target x86_64-linux-musl{{- end }}
        {{- if eq .Arch "arm64"}}CC=zig c++ -target aarch64-linux-musl{{- end }}
      {{- end }}

- id: pdfsigner-windows
  goos:
  - windows
  goarch:
  - amd64
  - arm64
  ldflags:
  - -s -w
  - -X main.BuildDate={{ .Date }}
  - -X main.Version={{ .Version }}
  - -X main.GitCommit={{ .FullCommit }}
  - -X main.GitBranch={{ .Branch }}
  flags:
  - -trimpath
  env:
  - CGO_ENABLED=1
  - >-
      {{- if eq .Os "windows" }}
        {{- if eq .Arch "amd64" }}CC=zig c -target x86_64-windows-gnu{{- end }}
        {{- if eq .Arch "arm64"}}CC=zig c -target aarch64-windows-gnu{{- end }}
      {{- end }}
  - >-
      {{- if eq .Os "windows" }}
        {{- if eq .Arch "amd64" }}CC=zig c++ -target x86_64-windows-gnu{{- end }}
        {{- if eq .Arch "arm64"}}CC=zig c++ -target aarch64-windows-gnu{{- end }}
      {{- end }}

archives:
  - formats: [ 'tar.gz' ]
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      formats: [ 'zip' ]
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'