licensePath = "./pdfsigner.lic"

# mixed command
[service1]
type = "watch"
signer = "signer1"
in = "path/to/inputfolder"
out = "path/to/outputfolder"
validateSignature = true

[serviceOther]
type = "serve"
signers = [ "signer1" ]
addr = "127.0.0.1"
port = 3000
validateSignature = true

# signers
[signer1]
type = "pem"
crtPath = "path/to/crt"
keyPath = "path/to/private/key"
crtChainPath = "path/to/certificate/chain"
[signer.signData.signature]
docMDP = 1
certType = 1
[signer.signData.signature.info]
name = "name"
location = "location"
reason = "reason"
contactInfo = "contact"

[signerOther]
type = "pksc11"
libPath = "path/to/lib"
pass = "path/to/lib"
crtChainPath = "path/to/certificate/chain"
[signer.signData.signature]
certType = 1
docMDP = 1
[signer.signData.signature.info]
name = "name"
location = "location"
reason = "reason"
contactInfo = "contact"
