# mixed command
[[service]]
name = "watch1"
type = "watch"
signer = "simple"
in = "path/to/inputfolder"
out = "path/to/outputfolder"

[[service]]
name = "web1"
type = "serve"
signers = [ "simple", "simple2" ]
port = 3000

# signers
[[signer]]
name = "simple"
type = "pem"
crtPath = "path/to/crt"
keyPath = "path/to/private/key"
crtChainPath = "path/to/certificate/chain"
[signer.signature]
approval = true
certType = 1
[signer.signature.info]
name = "name"
location = "location"
reason = "reason"
contactInfo = "contact"

[[signer]]
name = "simple2"
type = "pksc11"
libPath = "path/to/lib"
pass = "path/to/lib"
crtChainPath = "path/to/certificate/chain"
[signer.signature]
approval = true
certType = 1
[signer.signature.info]
name = "name"
location = "location"
reason = "reason"
contactInfo = "contact"
