# Main configuration
licensePath: /etc/pdfsigner/default.lic

# Common signature settings (anchor)
.signature_defaults: &signature_defaults
  docMDP: 1
  certType: 1

# Common signature info (anchor)
.signature_info_defaults: &signature_info_defaults
  name: Example Organization
  location: Amsterdam
  reason: Testing the Digitorus PDF Signer
  contactInfo: contact@example.com

# Services Configuration
services:
  watch_incoming:
    type: watch
    signer: default # Reference to the signer configuration below
    in: /var/lib/pdfsigner/input # Where to look for new PDFs
    out: /var/lib/pdfsigner/output # Where to put signed PDFs
    validateSignature: true # Verify signature after signing

  api_endpoint:
    type: serve
    signers:
      - default # List of allowed signers
    addr: localhost # Listen address
    port: 8080 # Listen port
    validateSignature: true

# Signers Configuration
signers:
  default:
    type: pem
    crtPath: /etc/pdfsigner/default.crt
    keyPath: /etc/pdfsigner/default.pem
    crtChainPath: /etc/pdfsigner/chain.pem
    signData:
      signature:
        <<: *signature_defaults # Reuse common signature settings
        info:
          <<: *signature_info_defaults # Reuse common info settings

  # hardware_token:
  #   type: pkcs11
  #   libPath: /usr/lib/softokn3.so
  #   pass: token_password
  #   crtChainPath: ./testfiles/test.crt
  #   signData:
  #     signature:
  #       <<: *signature_defaults # Reuse common signature settings
  #       info:
  #         name: Hardware Token
  #         location: Secure Element
  #         reason: Secure signing
  #         contactInfo: security@company.com
