// Code generated by "stringer -type=Priority"; DO NOT EDIT.

package priority_queue

import "fmt"

const _Priority_name = "UnknownPriorityLowPriorityMediumPriorityHighPriority"

var _Priority_index = [...]uint8{0, 15, 26, 40, 52}

func (i Priority) String() string {
	if i < 0 || i >= Priority(len(_Priority_index)-1) {
		return fmt.Sprintf("Priority(%d)", i)
	}
	return _Priority_name[_Priority_index[i]:_Priority_index[i+1]]
}
