name: GoReleaser

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
    paths-ignore:
    - 'docs/**'
    - '*.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - 'docs/**'
    - '*.md'

permissions:
  contents: write
  # packages: write
  # issues: write
  # id-token: write

jobs:
  goreleaser:
    name: Build and Release
    runs-on: ubuntu-latest
    env:
      flags: ''
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Zig
        uses: mlugg/setup-zig@v1

      - name: Check if release with tag or snapshot
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: echo "flags=--snapshot" >> $GITHUB_ENV

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --clean ${{ env.flags }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PDFSIGNER_LICENSE_PUBLIC_KEY: ${{ secrets.PDFSIGNER_LICENSE_PUBLIC_KEY }}
          PDFSIGNER_HMAC_KEY: ${{ secrets.PDFSIGNER_HMAC_KEY }}
          PDFSIGNER_LICENSE: ${{ secrets.PDFSIGNER_LICENSE }}
